server:
  port: 5002

spring:
  application:
    name: Subscription & Billing
  profiles:
    active: dev
  datasource:
    url: jdbc:oracle:thin:@//${ORACLE_HOST:localhost}:${ORACLE_PORT:1521}/${ORACLE_SERVICES:FREEPDB1}
    username: ${ORACLE_USER:subscription}
    password: ${ORACLE_PASSWORD:admin123}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 15
      maximum-pool-size: 300
      idle-timeout: 300000
      validation-timeout: 3000
      connection-timeout: 3000
      connection-test-query: SELECT 1 FROM DUAL
  cert:
    private-key: classpath:cert/private.pem
    public-key: classpath:cert/public.pem
  data:
#    kafka_servers: ${KAFKA_SERVERS:localhost:20001,localhost:20002,localhost:20003}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:libra123}
      timeout: 5s
      lettuce:
        pool:
          max-active: 50
          min-idle: 30
          max-idle: 20
          max-wait: 4s
  security:
    user:
      name: ${USER_SECURE}
      password: ${PASSWORD_SECURE}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USER_MAIL}
    password: ${PASSWORD_MAIL}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mybatis-plus:
  global-config:
    db-config:
      id-type: assign-id
    sequence:
      datacenter-id: 1
      worker-id: 1
    banner: false
  mapper-locations: mappers/*.xml
  configuration:
    map-underscore-to-camel-case: false